            - name: TruffleHog OSS
  # You may pin to the exact commit or the version.
  # uses: trufflesecurity/trufflehog@ef6e76c3c4023279497fab4721ffa071a722fd05
  uses: trufflesecurity/trufflehog@v3.92.4
  with:
    # Repository path
    path: # optional, default is ./
    # Start scanning from here (usually main branch).
    base: # optional, default is 
    # Scan commits until here (usually dev branch).
    head: # optional
    # Extra args to be passed to the trufflehog cli.
    extra_args: # optional, default is 
    # Scan with this trufflehog cli version.
    version: # optional, default is latest
          
